### ISSUE TITLE
Typo in solution 5.1

### ISSUE THREAD

**Issue by thegreatkwanghyeon** [frozenca/ML-Murphy#1]
In your solution 5.1 line 5,
I guess the denominator should be p(D | z=k), instead of p(\theta | z=k)

![sol](https://user-images.githubusercontent.com/33785899/76979828-d72a7800-697b-11ea-8d7c-a56bdddb1e19.jpg)

**Comment by frozenca** [comment]
You're right, I'll fix it.

**Comment by frozenca** [comment]
Fixed in 64c4041c.
