### ISSUE TITLE
What does /mu mean here? 

### ISSUE THREAD

**Issue by xdotli** [frozenca/ML-Murphy#2]
<img width="843" alt="Screen Shot 2022-03-05 at 23 14 32" src="https://user-images.githubusercontent.com/51786539/156889327-6d989bc3-31b7-4360-8129-6564b0de7d64.png">

**Comment by frozenca** [comment]
Please refer Exercise 8.4.
In Exercise 8.5, derivation of the formula is not exactly the same (because we have l_2 regularization term here), but the logic is almost the same
